"""OpaApprovalGate tests (Plan 16-03).

Posts request to OPA HTTP API /v1/data; result.allow boolean drives
approve/reject; missing result falls back to rejected per Assumption A2.
"""

from __future__ import annotations

import importlib
import json
import uuid
from pathlib import Path

import httpx
import respx

from sigantry_core.approval_gates.opa_hook import OpaApprovalGate
from sigantry_core.protocols import ApprovalContext, ApprovalGate


def _make_gate(
    *,
    opa_url: str = "http://localhost:8181",
    policy_path: str = "sigantry/approval/allow",
) -> OpaApprovalGate:
    return OpaApprovalGate(opa_url=opa_url, policy_path=policy_path)


def _make_request(gate: OpaApprovalGate):
    ctx = ApprovalContext(
        release_id="rel-2026-04-28",
        env="prod",
        approvers=["alice@example.com", "bob@example.com"],
    )
    return gate.request(ctx)


def test_satisfies_approval_gate_protocol() -> None:
    gate = _make_gate()
    assert isinstance(gate, ApprovalGate)
    assert gate.name == "opa"


def test_wait_returns_approved_when_result_true() -> None:
    """OPA returns {"result": True} -> outcome 'approved'."""
    captured: dict = {}
    with respx.mock(base_url="http://localhost:8181") as router:

        def _post_handler(request: httpx.Request) -> httpx.Response:
            captured["body"] = json.loads(request.content)
            return httpx.Response(200, json={"result": True})

        router.post("/v1/data/sigantry/approval/allow").mock(side_effect=_post_handler)
        gate = _make_gate()
        outcome = gate.wait(_make_request(gate))

    assert outcome == "approved"
    # The POST body carries the input shape the runbook documents.
    assert captured["body"] == {
        "input": {
            "release_id": "rel-2026-04-28",
            "env": "prod",
            "approvers": ["alice@example.com", "bob@example.com"],
        }
    }


def test_wait_returns_rejected_when_result_false() -> None:
    """OPA returns {"result": False} -> outcome 'rejected'."""
    with respx.mock(base_url="http://localhost:8181") as router:
        router.post("/v1/data/sigantry/approval/allow").mock(
            return_value=httpx.Response(200, json={"result": False})
        )
        gate = _make_gate()
        assert gate.wait(_make_request(gate)) == "rejected"


def test_wait_returns_rejected_when_result_missing() -> None:
    """RESEARCH §Assumption A2 defensive fallback: missing result -> rejected.

    The safe default for an undefined Rego decision is rejection. Approving
    on undefined would let a misconfigured policy silently auto-approve
    every deploy -- an unacceptable failure mode.
    """
    with respx.mock(base_url="http://localhost:8181") as router:
        router.post("/v1/data/sigantry/approval/allow").mock(
            return_value=httpx.Response(200, json={})  # no 'result' key
        )
        gate = _make_gate()
        assert gate.wait(_make_request(gate)) == "rejected"


def test_request_constructs_uuid4_request_id() -> None:
    """request() generates a fresh uuid4 every call.

    OPA has no native request id so the impl synthesises one. Two
    consecutive calls MUST produce distinct ids -- otherwise audit-log
    correlation would be broken.
    """
    gate = _make_gate()
    ctx = ApprovalContext(
        release_id="rel-2026-04-28",
        env="prod",
        approvers=["alice"],
    )
    r1 = gate.request(ctx)
    r2 = gate.request(ctx)
    assert r1.request_id != r2.request_id, "uuid4 ids must be unique"
    # Both must parse as valid uuid4.
    uuid.UUID(r1.request_id, version=4)
    uuid.UUID(r2.request_id, version=4)


def test_wait_emits_approval_record(tmp_path: Path) -> None:
    """Every decision emits an ApprovalRecord with decided_by='opa-policy'."""
    audit_mod = importlib.import_module("sigantry_core.governance.audit")
    original = audit_mod._DEFAULT_AUDIT_DIR
    audit_mod._DEFAULT_AUDIT_DIR = tmp_path
    try:
        with respx.mock(base_url="http://localhost:8181") as router:
            router.post("/v1/data/sigantry/approval/allow").mock(
                return_value=httpx.Response(200, json={"result": True})
            )
            gate = _make_gate()
            req = _make_request(gate)
            outcome = gate.wait(req)
    finally:
        audit_mod._DEFAULT_AUDIT_DIR = original

    assert outcome == "approved"
    record = json.loads((tmp_path / "approvals.jsonl").read_text("utf-8").splitlines()[0])
    assert record["outcome"] == "approved"
    assert record["decided_by"] == "opa-policy"
    assert record["release_id"] == "rel-2026-04-28"
    assert record["env"] == "prod"
    assert record["audit_hash"]
    # request_id is the uuid4 generated by request() -- must round-trip.
    assert record["request_id"] == req.request_id
