#!/usr/bin/env python3
"""
Documentation freshness gate.

WHY THIS EXISTS. Prose rules telling people to keep docs current have failed here
repeatedly: on 2026-08-13 three repositories were found publishing test counts,
coverage figures and version numbers that their own code contradicted, and two of
the worst offenders were the documents most likely to be circulated to senior
stakeholders. A rule cannot fail a build. This can.

WHAT IT CHECKS
  1. banned    - phrases known to be false, each carrying the reason it is false
  2. version   - the version declared in pyproject must be the one docs cite, and
                 no superseded version may be cited as current
  3. metrics   - numeric claims (tests, coverage) must match a measured metrics file

WHAT IT DELIBERATELY DOES NOT CHECK
  Point-in-time records: changelog entries for released versions, planning
  artifacts, dated audits, handoffs, archives. Those documented what was true when
  written; "correcting" them would falsify history. They are excluded by config.

CONFIG: `.docs-freshness.yml` at the repo root. See `--init` for a starter.

EXIT CODES: 0 clean, 1 drift found, 2 config/usage error.

    python docs_freshness.py                 # check the repo in cwd
    python docs_freshness.py --repo PATH
    python docs_freshness.py --selftest      # prove the gate can fail
"""

from __future__ import annotations

import argparse
import fnmatch
import json
import os
import re
import sys

# tomllib is stdlib only from 3.11, and these repos support 3.10. The gate has to
# run on the oldest Python the project claims to support, or it silently does not
# run there at all - which is the same as not having a gate.
try:
    import tomllib  # type: ignore[import-not-found]
except ModuleNotFoundError:
    try:
        import tomli as tomllib  # type: ignore[no-redef]
    except ModuleNotFoundError:
        tomllib = None  # type: ignore[assignment]

try:
    import yaml
except ImportError:  # keep the gate runnable without a yaml dep
    yaml = None

CONFIG_NAME = ".docs-freshness.yml"

STARTER = """\
# Documentation freshness gate. Run: python scripts/docs_freshness.py
#
# Point-in-time records are excluded on purpose - a changelog entry or a dated
# audit documented what was true when written, and rewriting it falsifies history.

scan:
  include:
    - "README.md"
    - "docs/**/*.md"
    - ".github/**/*.md"
  exclude:
    - "CHANGELOG.md"
    - "HANDOFF.md"
    - "**/archive/**"
    - "**/*AUDIT*"
    - ".planning/**"

# Optional: a measured metrics file, regenerated by CI. Keys are free-form.
metrics_file: "docs/metrics.json"

# Phrases that are known false. Each MUST carry the reason, so the failure
# message teaches rather than just blocks.
banned: []
#  - pattern: "300\\\\+ built-in"
#    why: "Measured 56 registered expectation implementations on GX 1.18.1"

# Superseded version strings that must not appear as the current version.
# The current version is read from pyproject and never hardcoded here.
retired_versions: []
#  - "1.5.0"
#  - "1.6.0"

# Numeric claims that must agree with metrics_file.
# `pattern` must contain exactly one capture group holding the number.
metric_claims: []
#  - pattern: "([0-9,]+) tests? (?:collected|passing)"
#    metric: tests_collected
#    why: "Test count must match the measured suite"
"""


# ---------------------------------------------------------------------------
# config + fact loading
# ---------------------------------------------------------------------------


def load_config(repo: str) -> dict:
    path = os.path.join(repo, CONFIG_NAME)
    if not os.path.exists(path):
        raise SystemExit(
            f"no {CONFIG_NAME} in {repo}\n"
            f"create one with:  python docs_freshness.py --init --repo {repo}"
        )
    with open(path, encoding="utf-8") as fh:
        text = fh.read()
    if yaml is None:
        raise SystemExit("pyyaml is required to read the config")
    cfg = yaml.safe_load(text) or {}
    cfg.setdefault("scan", {}).setdefault("include", ["README.md", "docs/**/*.md"])
    cfg["scan"].setdefault("exclude", [])
    cfg.setdefault("banned", [])
    cfg.setdefault("retired_versions", [])
    cfg.setdefault("metric_claims", [])
    return cfg


def _version_by_regex(pj: str) -> str | None:
    """Last-resort parse when no TOML reader is available.

    Scoped to the [project] table so a dependency pin or a tool section cannot
    be mistaken for the project version.
    """
    with open(pj, encoding="utf-8") as fh:
        text = fh.read()
    m = re.search(r"^\[project\](.*?)(?=^\[|\Z)", text, re.M | re.S)
    if not m:
        return None
    v = re.search(r'^\s*version\s*=\s*["\']([^"\']+)["\']', m.group(1), re.M)
    return v.group(1) if v else None


def declared_version(repo: str) -> str | None:
    """Read the version from pyproject, following a dynamic declaration."""
    pj = os.path.join(repo, "pyproject.toml")
    if not os.path.exists(pj):
        return None
    if tomllib is None:
        return _version_by_regex(pj)
    with open(pj, "rb") as fh:
        data = tomllib.load(fh)
    proj = data.get("project", {})
    if proj.get("version"):
        return proj["version"]
    # dynamic: find __version__ in the package __init__
    pkgs = (
        data.get("tool", {})
        .get("setuptools", {})
        .get("packages", {})
        .get("find", {})
        .get("include", [])
    )
    candidates = [p.rstrip("*").rstrip(".") for p in pkgs] or []
    name = (proj.get("name") or "").replace("-", "_")
    candidates.append(name)
    # A package commonly re-exports its version from a dedicated module
    # (`from pkg._version import __version__`), so the literal is not in
    # __init__.py at all. Check the usual homes before giving up - returning
    # None here would silently disable the retired-version check.
    for cand in candidates:
        for mod in ("__init__.py", "_version.py", "version.py"):
            path = os.path.join(repo, cand, mod)
            if not os.path.exists(path):
                continue
            with open(path, encoding="utf-8") as fh:
                m = re.search(r'^__version__\s*[:=]\s*["\']([^"\']+)["\']', fh.read(), re.M)
            if m:
                return m.group(1)
    return None


def load_metrics(repo: str, cfg: dict) -> dict:
    mf = cfg.get("metrics_file")
    if not mf:
        return {}
    path = os.path.join(repo, mf)
    if not os.path.exists(path):
        return {}
    with open(path, encoding="utf-8") as fh:
        return json.load(fh)


# ---------------------------------------------------------------------------
# file selection
# ---------------------------------------------------------------------------


def matches_any(rel: str, patterns: list[str]) -> bool:
    for pat in patterns:
        if fnmatch.fnmatch(rel, pat):
            return True
        # allow "docs/**/*.md" to also match "docs/x.md"
        if "**/" in pat and fnmatch.fnmatch(rel, pat.replace("**/", "")):
            return True
    return False


def scan_files(repo: str, cfg: dict) -> list[str]:
    inc = cfg["scan"]["include"]
    exc = cfg["scan"]["exclude"]
    found: list[str] = []
    for dirpath, dirnames, filenames in os.walk(repo):
        dirnames[:] = [
            d
            for d in dirnames
            if d
            not in {".git", "node_modules", "__pycache__", ".mypy_cache", ".pytest_cache", "site"}
        ]
        for fn in filenames:
            full = os.path.join(dirpath, fn)
            rel = os.path.relpath(full, repo).replace(os.sep, "/")
            if matches_any(rel, inc) and not matches_any(rel, exc):
                found.append(rel)
    return sorted(set(found))


# ---------------------------------------------------------------------------
# checks
# ---------------------------------------------------------------------------

ALLOW_MARKER = "docs-freshness: allow"


def check(repo: str, cfg: dict) -> list[str]:
    problems: list[str] = []
    version = declared_version(repo)
    metrics = load_metrics(repo, cfg)
    files = scan_files(repo, cfg)

    if not files:
        problems.append(
            "scan matched ZERO files - the gate would pass vacuously. Check scan.include patterns."
        )
        return problems

    for rel in files:
        with open(os.path.join(repo, rel), encoding="utf-8", errors="replace") as fh:
            lines = fh.readlines()

        # A correction note has to quote the wrong value in order to correct it,
        # and a deploy record has to name the version that was actually deployed.
        # Without an escape hatch this gate fires on exactly the writing that
        # fixes the problem - so an explicit, greppable marker exempts a line or
        # the block that follows it. The marker is deliberately verbose: it
        # should be obvious in review that an exemption was taken.
        exempt: set[int] = set()
        block_open = False
        for idx, line in enumerate(lines, 1):
            if ALLOW_MARKER in line:
                exempt.add(idx)
                if "start" in line:
                    block_open = True
                if "end" in line:
                    block_open = False
            elif block_open:
                exempt.add(idx)

        for i, line in enumerate(lines, 1):
            # A marker on the preceding line exempts this one, which is the
            # common case: the marker sits above the text it excuses.
            preceded_by_marker = i > 1 and ALLOW_MARKER in lines[i - 2]
            if i in exempt or preceded_by_marker:
                continue
            for ban in cfg["banned"]:
                if re.search(ban["pattern"], line, re.I):
                    problems.append(
                        f"{rel}:{i}: banned claim /{ban['pattern']}/ - {ban['why']}\n"
                        f"    {line.strip()[:120]}"
                    )

            for old in cfg["retired_versions"]:
                if re.search(rf"(?<![\d.]){re.escape(str(old))}(?![\d.])", line):
                    problems.append(
                        f"{rel}:{i}: retired version {old} (current is {version})\n"
                        f"    {line.strip()[:120]}"
                    )

            for claim in cfg["metric_claims"]:
                m = re.search(claim["pattern"], line, re.I)
                if not m:
                    continue
                key = claim["metric"]
                if key not in metrics:
                    problems.append(
                        f"{rel}:{i}: claim references metric '{key}' "
                        f"which is absent from the metrics file"
                    )
                    continue
                got = m.group(1).replace(",", "")
                want = str(metrics[key]).replace(",", "")
                if got != want:
                    problems.append(
                        f"{rel}:{i}: states {got} for '{key}', measured {want}"
                        f" - {claim.get('why', '')}\n    {line.strip()[:120]}"
                    )
    return problems


# ---------------------------------------------------------------------------
# selftest - the gate must be shown to FAIL before it is trusted
# ---------------------------------------------------------------------------


def selftest() -> int:
    import tempfile

    def build(tmp: str, doc: str, cfg_extra: str = "") -> None:
        os.makedirs(os.path.join(tmp, "docs"), exist_ok=True)
        with open(os.path.join(tmp, "pyproject.toml"), "w") as fh:
            fh.write('[project]\nname = "demo"\nversion = "2.0.0"\n')
        with open(os.path.join(tmp, "docs", "guide.md"), "w") as fh:
            fh.write(doc)
        with open(os.path.join(tmp, "metrics.json"), "w") as fh:
            json.dump({"tests_collected": 544}, fh)
        with open(os.path.join(tmp, CONFIG_NAME), "w") as fh:
            fh.write(
                'scan:\n  include: ["docs/**/*.md"]\n  exclude: ["**/archive/**"]\n'
                'metrics_file: "metrics.json"\n' + cfg_extra
            )

    cases = {
        "banned phrase": (
            "We ship 300+ built-in validations.\n",
            'banned:\n  - pattern: "300\\\\+ built-in"\n    why: "measured 56"\n',
        ),
        "retired version cited as current": (
            "Install version 1.5.0 today.\n",
            'retired_versions: ["1.5.0"]\n',
        ),
        "metric drift": (
            "The suite has 74 tests collected.\n",
            'metric_claims:\n  - pattern: "([0-9,]+) tests? collected"\n'
            '    metric: tests_collected\n    why: "must match suite"\n',
        ),
        "vacuous scan (matches nothing)": ("irrelevant\n", ""),
    }

    ok = True
    for name, (doc, extra) in cases.items():
        with tempfile.TemporaryDirectory() as tmp:
            if name.startswith("vacuous"):
                os.makedirs(os.path.join(tmp, "docs"), exist_ok=True)
                with open(os.path.join(tmp, CONFIG_NAME), "w") as fh:
                    fh.write('scan:\n  include: ["nonexistent/**/*.md"]\n  exclude: []\n')
                with open(os.path.join(tmp, "pyproject.toml"), "w") as fh:
                    fh.write('[project]\nname="d"\nversion="1.0.0"\n')
            else:
                build(tmp, doc, extra)
            found = check(tmp, load_config(tmp))
            status = "DETECTED" if found else "MISSED  <-- gate is vacuous"
            print(f"  break-arm [{name}]: {status}")
            if found:
                print(f"      {found[0].splitlines()[0]}")
            ok = ok and bool(found)

    # The allow-marker needs BOTH arms proved, or it is either useless or a
    # blanket bypass: the same content must FAIL unmarked and PASS marked.
    ban_cfg = 'banned:\n  - pattern: "300\\\\+ built-in"\n    why: "measured 56"\n'
    with tempfile.TemporaryDirectory() as tmp:
        build(tmp, "We used to claim 300+ built-in validations.\n", ban_cfg)
        unmarked = check(tmp, load_config(tmp))
    with tempfile.TemporaryDirectory() as tmp:
        build(
            tmp,
            "<!-- docs-freshness: allow -->\nWe used to claim 300+ built-in validations.\n",
            ban_cfg,
        )
        marked = check(tmp, load_config(tmp))
    good = bool(unmarked) and not marked
    print(
        f"  allow-marker: unmarked={'FAILS' if unmarked else 'passes'} "
        f"marked={'FAILS' if marked else 'passes'} "
        f"-> {'CORRECT' if good else 'BROKEN'}"
    )
    ok = ok and good

    # closing clean arm: a correct repo must produce zero problems, else the
    # gate merely rejects everything and proves nothing
    with tempfile.TemporaryDirectory() as tmp:
        build(
            tmp,
            "Install version 2.0.0. The suite has 544 tests collected.\n",
            'retired_versions: ["1.5.0"]\n'
            'banned:\n  - pattern: "300\\\\+ built-in"\n    why: "measured 56"\n'
            'metric_claims:\n  - pattern: "([0-9,]+) tests? collected"\n'
            '    metric: tests_collected\n    why: "must match suite"\n',
        )
        found = check(tmp, load_config(tmp))
        print(f"  clean arm : {'PASS (0 problems)' if not found else 'FAIL ' + str(found)}")
        ok = ok and not found

    return 0 if ok else 1


def main() -> int:
    ap = argparse.ArgumentParser(description="Documentation freshness gate")
    ap.add_argument("--repo", default=os.getcwd())
    ap.add_argument("--init", action="store_true", help=f"write a starter {CONFIG_NAME}")
    ap.add_argument("--selftest", action="store_true")
    args = ap.parse_args()

    if args.selftest:
        print("docs-freshness gate self-test (each break MUST be detected):")
        return selftest()

    if args.init:
        dest = os.path.join(args.repo, CONFIG_NAME)
        if os.path.exists(dest):
            print(f"{dest} already exists; not overwriting")
            return 2
        with open(dest, "w", encoding="utf-8") as fh:
            fh.write(STARTER)
        print(f"wrote {dest}")
        return 0

    cfg = load_config(args.repo)
    problems = check(args.repo, cfg)
    scanned = len(scan_files(args.repo, cfg))
    if problems:
        print(f"DOCS FRESHNESS: {len(problems)} problem(s) across {scanned} scanned file(s)\n")
        for p in problems:
            print(f"  - {p}")
        print(
            "\nFix the document, or - if the document is a point-in-time record - "
            "add it to scan.exclude with a comment saying why."
        )
        return 1
    print(f"DOCS FRESHNESS: clean ({scanned} files scanned)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
