"""Audit-2026-05-07 W3.3 -- meta-gate: ``requirements-lock.txt`` is
hash-pinned and generated under Python 3.11.

Pre-W3.3 the lockfile carried only ``==<version>`` pins -- not
``--hash=sha256:...`` lines. That meant a compromised PyPI mirror
could swap the artifact for a malicious one matching the version
without pip detecting it (no checksum comparison). Hash pinning
closes that gap. The lockfile was also generated under Python 3.12
(per ``# This file is autogenerated by pip-compile with Python 3.12``)
even though the project pins ``requires-python = ">=3.11,<3.13"`` and
the conda env ships 3.11; this means dev-tooling resolutions were
3.12-specific. W3.3 regenerated under 3.11.

This test pins both invariants:

- Every ``<package>==<version>`` line is followed by at least one
  ``--hash=sha256:...`` clause.
- The lockfile header records ``Python 3.11`` (the conda env's
  pinned major.minor).

Falsifiability: a regeneration that drops ``--generate-hashes`` or
runs under Python 3.12 fails this gate.
"""

from __future__ import annotations

import re
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
LOCKFILE = REPO_ROOT / "requirements-lock.txt"


def test_lockfile_exists() -> None:
    assert LOCKFILE.is_file(), (
        "requirements-lock.txt is missing. The W3.3 decision was to "
        "REGENERATE under Python 3.11 with hashes, not delete."
    )


def test_lockfile_header_records_python_311() -> None:
    """The pip-compile header records the Python version. Must be 3.11."""
    text = LOCKFILE.read_text(encoding="utf-8")
    # The autogen header looks like:
    # ``# This file is autogenerated by pip-compile with Python 3.11``
    m = re.search(r"pip-compile with Python (\d+\.\d+)", text)
    assert m is not None, (
        "requirements-lock.txt is missing the pip-compile autogen header. "
        "Regenerate via `pip-compile --extra=dev --generate-hashes "
        "--output-file=requirements-lock.txt --strip-extras pyproject.toml`."
    )
    assert m.group(1) == "3.11", (
        f"requirements-lock.txt was generated under Python {m.group(1)}; "
        "expected 3.11 (the conda env pin). Regenerate inside "
        "`/home/sanmi/miniconda3/envs/fabric-dataops-toolkits/`."
    )


def test_lockfile_uses_generate_hashes() -> None:
    """The autogen header includes the ``--generate-hashes`` flag."""
    text = LOCKFILE.read_text(encoding="utf-8")
    assert "--generate-hashes" in text, (
        "requirements-lock.txt was not generated with --generate-hashes. "
        "A version-only lockfile lets a compromised mirror swap the "
        "artifact undetected. Regenerate with --generate-hashes."
    )


def test_every_pinned_package_has_at_least_one_hash() -> None:
    """Every ``<pkg>==<ver>`` line is followed by ``--hash=sha256:...``.

    Falsifiability: deleting any ``--hash=`` line trips this test on the
    next CI run.
    """
    text = LOCKFILE.read_text(encoding="utf-8")
    lines = text.splitlines()
    offenders: list[str] = []
    for i, line in enumerate(lines):
        # Match a top-level pin: ``<pkg>==<version> \`` or
        # ``<pkg>==<version>`` (no continuation; pip-compile always
        # emits backslash + newline followed by --hash lines).
        stripped = line.split("#", 1)[0].strip()
        m = re.match(r"^([a-zA-Z0-9._-]+)==[^\s\\]+\s*\\?$", stripped)
        if not m:
            continue
        pkg = m.group(1)
        # Look forward for at least one --hash line on the
        # immediately-following lines (terminated by blank or another pin).
        has_hash = False
        for j in range(i + 1, min(i + 50, len(lines))):
            nxt = lines[j].strip()
            if not nxt or nxt.startswith("#"):
                # Blank or comment -- end of the pin block; stop searching.
                break
            if nxt.startswith("--hash="):
                has_hash = True
                break
            # If we hit another pin first, the previous pin had no hash.
            if re.match(r"^[a-zA-Z0-9._-]+==", nxt):
                break
        if not has_hash:
            offenders.append(f"line {i + 1}: {pkg}")
    assert offenders == [], (
        "Pinned packages missing --hash= lines (W3.3 supply-chain gate):\n"
        "  - " + "\n  - ".join(offenders)
    )


def test_lockfile_excludes_extras_strip_extras() -> None:
    """Lockfile uses ``--strip-extras`` to avoid ``[extra]`` qualifiers.

    Pip in older versions did not honour extras in lockfile lines
    correctly; ``--strip-extras`` makes the file portable across pip
    versions.
    """
    text = LOCKFILE.read_text(encoding="utf-8")
    assert "--strip-extras" in text, (
        "requirements-lock.txt header does not record --strip-extras. "
        "Regenerate with that flag for portability across pip versions."
    )


def test_lockfile_does_not_pin_extras_in_package_specs() -> None:
    """No ``<pkg>[extra]==<ver>`` lines (a side-effect of --strip-extras)."""
    text = LOCKFILE.read_text(encoding="utf-8")
    offenders: list[str] = []
    for i, line in enumerate(text.splitlines(), 1):
        stripped = line.split("#", 1)[0].strip()
        if re.match(r"^[a-zA-Z0-9._-]+\[[a-zA-Z0-9_,\-]+\]==", stripped):
            offenders.append(f"line {i}: {stripped}")
    assert offenders == [], (
        "Package specs with [extra] qualifiers found in requirements-lock.txt. "
        "Re-run pip-compile with --strip-extras.\n  - " + "\n  - ".join(offenders)
    )
